server:
  port: 6001
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl11
    driver-class-name: "oracle.jdbc.OracleDriver"
    username: system
    password: pinku
  jpa:
    database: ORACLE
    generate-ddl: true
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
       globally_quoted_identifiers: true
       
      
